-- 0. Garantir Unicidade nos IDs Numéricos (Necessário para Chaves Estrangeiras)
DO $$ 
BEGIN 
    -- Garante que pacientes(seqid) seja único
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pacientes_seqid_unique') THEN
        ALTER TABLE public.pacientes ADD CONSTRAINT pacientes_seqid_unique UNIQUE (seqid);
    END IF;

    -- Garante que profissionais(seqid) seja único
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profissionais_seqid_unique') THEN
        ALTER TABLE public.profissionais ADD CONSTRAINT profissionais_seqid_unique UNIQUE (seqid);
    END IF;
END $$;

-- 1. Tabela de Transações (A "Conta Corrente")
CREATE TABLE IF NOT EXISTS public.financeiro_transacoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seqid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    paciente_id BIGINT REFERENCES public.pacientes(seqid) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('CREDITO', 'DEBITO')),
    categoria TEXT NOT NULL CHECK (categoria IN ('PAGAMENTO', 'TRANSFERENCIA', 'ESTORNO', 'REEMBOLSO')),
    valor NUMERIC(10, 2) NOT NULL,
    data_transacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    forma_pagamento TEXT, -- Opcional: PIX, Cartão, etc.
    referencia_id BIGINT,  -- Pode ser o ID do Orçamento ou Item
    paciente_destino_id BIGINT REFERENCES public.pacientes(seqid), -- Para transferências
    observacoes TEXT,
    notificado_email BOOLEAN DEFAULT FALSE, -- Controle de envio de comprovante
    empresa_id TEXT REFERENCES public.empresas(id) ON DELETE CASCADE, -- Corrigido para TEXT
    criado_por UUID REFERENCES auth.users(id)
);

-- 2. Tabela de Comissões
CREATE TABLE IF NOT EXISTS public.financeiro_comissoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seqid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profissional_id BIGINT REFERENCES public.profissionais(seqid) ON DELETE CASCADE,
    item_id TEXT REFERENCES public.orcamento_itens(id) ON DELETE CASCADE, -- Corrigido para TEXT
    valor_comissao NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDENTE', -- 'PENDENTE', 'GERADA', 'PAGA', 'ESTORNADA'
    data_geracao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    transacao_estorno_id UUID REFERENCES public.financeiro_transacoes(id),
    empresa_id TEXT REFERENCES public.empresas(id) ON DELETE CASCADE -- Corrigido para TEXT
);

-- 3. Ajuste na Tabela de Orçamentos (Tipo de Fluxo)
ALTER TABLE public.orcamentos ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'Normal' CHECK (tipo IN ('Normal', 'Urgencia'));

-- 3. Índices para Auditoria
CREATE INDEX IF NOT EXISTS idx_transacoes_paciente ON public.financeiro_transacoes(paciente_id);
CREATE INDEX IF NOT EXISTS idx_comissoes_profissional ON public.financeiro_comissoes(profissional_id);
CREATE INDEX IF NOT EXISTS idx_comissoes_item ON public.financeiro_comissoes(item_id);

-- 4. Função para calcular Saldo Atual (View)
CREATE OR REPLACE VIEW public.view_saldo_paciente AS
SELECT 
    paciente_id,
    SUM(CASE WHEN tipo = 'CREDITO' THEN valor ELSE -valor END) as saldo_atual
FROM public.financeiro_transacoes
GROUP BY paciente_id;

-- NOTA ANALÍTICA:
-- 1. TRANSFERÊNCIA: Uma transferência de A para B gera dois registros nesta tabela.
-- 2. RETRABALHO: Se um item for cancelado/refeito, o status da comissão muda para 'ESTORNADA' 
--    e um registro de débito é gerado para o profissional (ou desconto na próxima guia).
-- 3. REEMBOLSO: É um débito direto na conta corrente com categoria 'REEMBOLSO'.
