-- ORCAMENTO PAGAMENTOS - FASE 3
-- Este script implementa a base para a gestão de pagamentos e liberação clínica.

-- 1. Tabela de Pagamentos (Financeiro)
-- Mantém a rastreabilidade de cada valor recebido vinculado ao orçamento.
CREATE TABLE IF NOT EXISTS public.orcamento_pagamentos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seqid BIGINT GENERATED BY DEFAULT AS IDENTITY, -- ID incremental para exibição
    orcamento_id BIGINT REFERENCES public.orcamentos(seqid) ON DELETE CASCADE,
    valor_pago NUMERIC(10, 2) NOT NULL,
    data_pagamento TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    forma_pagamento TEXT NOT NULL CHECK (forma_pagamento IN ('PIX', 'Cartão', 'Dinheiro', 'Boleto', 'Cheque')),
    status_pagamento TEXT NOT NULL DEFAULT 'Confirmado' CHECK (status_pagamento IN ('Confirmado', 'Pendente', 'Cancelado', 'Compensando')),
    tenant_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE,
    observacoes TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Padronização de Status nos Itens (Fluxo Clínico)
-- O campo 'status' agora deve refletir a jornada do item:
-- 'Pendente' -> 'Aguardando Pagamento' -> 'Liberado' -> 'Em Execução' -> 'Finalizado'

-- Garante que a coluna exista (caso não tenha sido criada em migrações anteriores)
ALTER TABLE public.orcamento_itens 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pendente';

-- 3. Índices para Performance
CREATE INDEX IF NOT EXISTS idx_pagamentos_orcamento ON public.orcamento_pagamentos(orcamento_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_tenant ON public.orcamento_pagamentos(tenant_id);

-- NOTA PARA DISCUSSÃO:
-- Implementaremos uma lógica no frontend (app.js) que calcula o TOTAL PAGO vs TOTAL ORÇADO.
-- Se TOTAL PAGO >= TOTAL ORÇADO, o sistema pode sugerir a LIBERAÇÃO TOTAL automática.
-- Caso contrário, o usuário libera manualmente item por item conforme o pagamento evolui.
