begin;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce(auth.jwt() ->> 'email', current_setting('request.jwt.claim.email', true), '') = 'lhbr@lhbr.com.br';
$$;

grant execute on function public.is_superadmin() to authenticated;

create or replace function public.is_member_of_empresa(target_empresa_id text)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.usuario_empresas ue
    where ue.usuario_id::text = auth.uid()::text
      and ue.empresa_id = target_empresa_id
  );
$$;

grant execute on function public.is_member_of_empresa(text) to authenticated;

create table if not exists public.protese_contas_pagar (
  id uuid primary key default gen_random_uuid(),
  seqid bigint generated by default as identity,
  empresa_id text not null references public.empresas(id) on delete cascade,
  ordem_id uuid not null references public.ordens_proteticas(id) on delete cascade,
  orcamento_id text,
  orcamento_item_id text,
  destinatario_tipo text not null,
  protetico_id text,
  laboratorio_id uuid,
  valor numeric(10,2) not null default 0,
  vencimento date,
  status text not null default 'PENDENTE',
  pago_em timestamptz,
  pago_por uuid references auth.users(id),
  transacao_id uuid references public.financeiro_transacoes(id),
  created_at timestamptz not null default timezone('utc'::text, now()),
  created_by uuid references auth.users(id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'protese_contas_pagar_destinatario_tipo_chk'
  ) then
    alter table public.protese_contas_pagar
      add constraint protese_contas_pagar_destinatario_tipo_chk
      check (destinatario_tipo in ('LABORATORIO','PROTETICO_INTERNO'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'protese_contas_pagar_status_chk'
  ) then
    alter table public.protese_contas_pagar
      add constraint protese_contas_pagar_status_chk
      check (status in ('PENDENTE','PAGO','CANCELADA'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'protese_contas_pagar_dest_fk_lab'
  ) then
    alter table public.protese_contas_pagar
      add constraint protese_contas_pagar_dest_fk_lab
      foreign key (laboratorio_id)
      references public.laboratorios_proteticos(id)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'protese_contas_pagar_dest_fk_prot'
  ) then
    alter table public.protese_contas_pagar
      add constraint protese_contas_pagar_dest_fk_prot
      foreign key (protetico_id)
      references public.profissionais(id)
      on delete restrict;
  end if;
end $$;

create unique index if not exists protese_contas_pagar_empresa_ordem_uniq
on public.protese_contas_pagar (empresa_id, ordem_id);

create index if not exists protese_contas_pagar_empresa_status_idx
on public.protese_contas_pagar (empresa_id, status, vencimento);

alter table public.protese_contas_pagar enable row level security;

drop policy if exists "Users can view protese payables of their company" on public.protese_contas_pagar;
create policy "Users can view protese payables of their company"
on public.protese_contas_pagar
for select
using (public.is_member_of_empresa(protese_contas_pagar.empresa_id) or public.is_superadmin());

drop policy if exists "Admins can insert protese payables of their company" on public.protese_contas_pagar;
create policy "Admins can insert protese payables of their company"
on public.protese_contas_pagar
for insert
with check (public.is_admin_of_empresa(protese_contas_pagar.empresa_id) or public.is_superadmin());

drop policy if exists "Admins can update protese payables of their company" on public.protese_contas_pagar;
create policy "Admins can update protese payables of their company"
on public.protese_contas_pagar
for update
using (public.is_admin_of_empresa(protese_contas_pagar.empresa_id) or public.is_superadmin())
with check (public.is_admin_of_empresa(protese_contas_pagar.empresa_id) or public.is_superadmin());

create or replace function public.rpc_refresh_protese_conta_pagar(p_empresa_id text, p_ordem_id uuid)
returns void
language plpgsql
security invoker
as $$
declare
  v_ord public.ordens_proteticas%rowtype;
  v_val numeric(10,2);
  v_venc date;
  v_tipo text;
begin
  select *
  into v_ord
  from public.ordens_proteticas
  where empresa_id = p_empresa_id
    and id = p_ordem_id;

  if not found then
    return;
  end if;

  if coalesce(v_ord.status_geral, '') <> 'CONCLUIDA' then
    update public.protese_contas_pagar
    set status = 'CANCELADA'
    where empresa_id = p_empresa_id
      and ordem_id = p_ordem_id
      and status = 'PENDENTE';
    return;
  end if;

  if v_ord.orcamento_item_id is null or v_ord.orcamento_item_id = '' then
    return;
  end if;

  select coalesce(oi.valor_protetico, 0)
  into v_val
  from public.orcamento_itens oi
  where oi.empresa_id = p_empresa_id
    and oi.id = v_ord.orcamento_item_id;

  if coalesce(v_val, 0) <= 0 then
    return;
  end if;

  if coalesce(v_ord.tipo_execucao, '') = 'EXTERNA' then
    v_tipo := 'LABORATORIO';
    select (timezone('utc'::text, now())::date + coalesce(lp.prazo_padrao_dias, 0))
    into v_venc
    from public.laboratorios_proteticos lp
    where lp.id = v_ord.laboratorio_id;
  else
    v_tipo := 'PROTETICO_INTERNO';
    v_venc := timezone('utc'::text, now())::date;
  end if;

  insert into public.protese_contas_pagar (
    empresa_id,
    ordem_id,
    orcamento_id,
    orcamento_item_id,
    destinatario_tipo,
    protetico_id,
    laboratorio_id,
    valor,
    vencimento,
    status,
    created_by
  )
  values (
    p_empresa_id,
    p_ordem_id,
    nullif(v_ord.orcamento_id, ''),
    nullif(v_ord.orcamento_item_id, ''),
    v_tipo,
    nullif(v_ord.protetico_id, ''),
    v_ord.laboratorio_id,
    v_val,
    v_venc,
    'PENDENTE',
    auth.uid()
  )
  on conflict (empresa_id, ordem_id) do update
    set
      orcamento_id = excluded.orcamento_id,
      orcamento_item_id = excluded.orcamento_item_id,
      destinatario_tipo = excluded.destinatario_tipo,
      protetico_id = excluded.protetico_id,
      laboratorio_id = excluded.laboratorio_id,
      valor = excluded.valor,
      vencimento = excluded.vencimento
    where protese_contas_pagar.status = 'PENDENTE';
end;
$$;

grant execute on function public.rpc_refresh_protese_conta_pagar(text, uuid) to authenticated;

create or replace function public.trg_ordem_protetica_refresh_conta_pagar()
returns trigger
language plpgsql
security invoker
as $$
begin
  if tg_op = 'UPDATE' then
    if coalesce(old.status_geral, '') is distinct from coalesce(new.status_geral, '') then
      perform public.rpc_refresh_protese_conta_pagar(new.empresa_id, new.id);
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists ordens_proteticas_refresh_conta_pagar on public.ordens_proteticas;
create trigger ordens_proteticas_refresh_conta_pagar
after update of status_geral on public.ordens_proteticas
for each row
execute function public.trg_ordem_protetica_refresh_conta_pagar();

notify pgrst, 'reload schema';

commit;

