begin;

create extension if not exists pgcrypto;

create table if not exists public.agenda_disponibilidade (
  id uuid primary key default gen_random_uuid(),
  seqid bigint generated by default as identity,

  empresa_id text not null references public.empresas(id) on delete cascade,
  profissional_id bigint not null references public.profissionais(seqid) on delete cascade,

  dia_semana int not null check (dia_semana between 1 and 7),
  hora_inicio time not null,
  hora_fim time not null,

  slot_minutos int not null default 30 check (slot_minutos in (5,10,15,20,30,45,60)),
  ativo boolean not null default true,

  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),

  constraint agenda_disponibilidade_horario_ok check (hora_fim > hora_inicio),
  constraint agenda_disponibilidade_unique unique (empresa_id, profissional_id, dia_semana, hora_inicio, hora_fim)
);

create index if not exists idx_agenda_disp_empresa_prof_dia on public.agenda_disponibilidade (empresa_id, profissional_id, dia_semana);

commit;
