begin;

create extension if not exists pgcrypto;

create table if not exists public.agenda_agendamentos (
  id uuid primary key default gen_random_uuid(),
  seqid bigint generated by default as identity,

  empresa_id text not null references public.empresas(id) on delete cascade,
  profissional_id bigint not null references public.profissionais(seqid) on delete cascade,
  paciente_id bigint references public.pacientes(seqid) on delete set null,

  inicio timestamptz not null,
  fim timestamptz not null,
  status text not null default 'MARCADO' check (status in ('MARCADO','CANCELADO','CONCLUIDO','FALTOU')),

  titulo text,
  observacoes text,

  criado_por uuid references auth.users(id),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),

  constraint agenda_agendamentos_intervalo_ok check (fim > inicio)
);

create index if not exists idx_agenda_agendamentos_empresa_prof_inicio on public.agenda_agendamentos (empresa_id, profissional_id, inicio);
create index if not exists idx_agenda_agendamentos_empresa_inicio on public.agenda_agendamentos (empresa_id, inicio);
create index if not exists idx_agenda_agendamentos_paciente on public.agenda_agendamentos (empresa_id, paciente_id);

commit;

